const config = {
    MONGODB_USERNAME: '',
    MONGODB_PASSWORD: '',
    MONGODB_HOST: '',
    MONGODB_PORT: 27115,
    MONGODB_DATABASE_NAME: '',
    MLAB_USER: 'admin',
    MLAB_PASSWORD: 'admin123',
    TOKEN_SECRET: 'dummytokensecrethere',
    ACCESS_TOKEN_EXPIRY: '7d',
    ACCESS_TOKEN_ALGO: 'HS256',
    REFRESH_TOKEN_EXPIRY: '7d',
    REFRESH_TOKEN_ALGO: 'HS384',
    PASS_HASH_ROUNDS: 10,
    SENDGRID_API_KEY: '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',
    AWS_SECRET_ACCESS: 'tXjTJS1tTQlWKMhPmSpCyuLDHpUB4RyEc1iFnP3G',
    AWS_ACCESS_KEY: 'AKIAJPMWSZTBZYRMCAQA',
    FCM_URL: "https://fcm.googleapis.com/fcm/send",
    FCM_KEY: "key=AAAA96_DIlE:APA91bHTc3W1lhso8EpRzSiO-E64avBBccoZFFfRhZCKK0o54KfTrBz3vgdsDwa17U7Bo0ctPdSF7t-jyOhexCUPEBTTSCtJcmzc1hgZxZ1OP9TytXxnqLQCnszSU6ttm8bq2ncC466i"

};

export default config;